using App.AutoGenerated;
using Axon_Job_App.Data;
using Microsoft.EntityFrameworkCore;

var builder = WebApplication.CreateBuilder(args);

builder.useCai();

// Configuration
var configuration = builder.Configuration;
var connString = configuration.GetConnectionString("DevDB");

// Database Context - register first without scoped registration
builder.Services.AddDbContext<DataContext>(options => 
    options.UseSqlite(connString));

builder.Services.AddControllers();

//Cors
builder.Services.AddCors(options =>
{
    options.AddDefaultPolicy(policy =>
    {
        policy.AllowAnyOrigin()
              .AllowAnyMethod()
              .AllowAnyHeader();
    });
});

var app = builder.Build();

// Configure the HTTP request pipeline.
if (app.Environment.IsDevelopment())
{
    app.UseDeveloperExceptionPage();
}


app.UseHttpsRedirection();

app.UseCors();

app.MigrateDb();

app.MapControllers();

app.mapCai(); 

app.Run();

