using App.AutoGenerated.Domain;
using Axon_Job_App.Features.Clients;
using Cai;

namespace Axon_Job_App.Features.Jobs;


public class JobSubscription
{
    // Static for all new Jobs
    [Subscription<JobResponse>(name = "OnJobCreated", topic = "JobCreated")]
    public record JobCreated();

    // Dynamic for a specific job
    [Subscription<JobResponse>(name = "OnJobUpdated", topic = "JobUpdated")]
    public record JobUpdated(long Id);

    public static string Handle(GetSubscriptionTopic<Job> input) => $"jobUpdated_{input.input.Id}";

}